// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package rating

import (
	"time"
)

type Bgrating struct {
	ID            int32
	Rating        int32
	CharName      string
	CharGuildName string
	CharLevel     int32
	BattlesCount  int32
	LastMatchTime time.Time
}
